sudo: required
dist: trusty
# https://github.com/travis-ci/docker-sinatra/blob/master/Dockerfile
language: python
python: '2.7'
script: sudo bash upgrade.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
