sudo: required
dist: trusty
# https://github.com/travis-ci/docker-sinatra/blob/master/Dockerfile
language: python
python: '2.7'
script: sh -c 'echo "y\n\n" | DEBIAN_FRONTEND=noninteractive /usr/bin/do-release-upgrade'
after_success:
- bash <(curl -s https://codecov.io/bash)
